separator_color = "white"
key_color = "blue"
prefer_small_ascii = true

[randomize]
key_color = false
separator_color = false

[custom_ascii]
color = "blue"
path = "~/dotfiles/.config/macchina/themes/ascii_fedora.txt"

[keys]
host = " host"
kernel = " kernel"
distro = " distro"
packages = " packages"
terminal = " terminal"
shell = " shell"
cpu = " cpu"
cpu_load = " cpu"
memory = " memory"
battery = " battery"
