require("trouble").setup({
    position = "bottom",
    height = 10,
    width = 50,
    icons = true,
    signs = {
        error = " ",
        warning = " ",
        hint = " ",
        information = " ",
        other = " ",
    },
    mode = "document_diagnostics",
    action_keys = {
        close = "q",
        cancel = "<esc>",
        refresh = "r",
        jump = { "<cr>", "<tab>" },
        open_split = { "<c-x>" },
        open_vsplit = { "<c-v>" },
        open_tab = { "<c-t>" },
        jump_close = { "o" },
        toggle_mode = "m",
        toggle_preview = "P",
        hover = "K",
        preview = "p",
        close_folds = { "zM", "zm" },
        open_folds = { "zR", "zr" },
        toggle_fold = { "zA", "za" },
        previous = "k",
        next = "j",
    },
    indent_lines = true,
    auto_open = false,
    auto_close = false,
    auto_preview = true,
    use_diagnostic_signs = false,
    auto_fold = false,
    use_lsp_diagnostic_signs = false,
})
