gui:
    theme:
        lightTheme: false
        # inactiveBorderColor:
        #     - "#cdd6f4" # Text
        # optionsTextColor:
        #     - "#89b4fa" # Blue
        # selectedLineBgColor:
        #     - "#313244" # Surface0
        # selectedRangeBgColor:
        #     - "#313244" # Surface0
        # cherryPickedCommitBgColor:
        #     - "#94e2d5" # Teal
        # cherryPickedCommitFgColor:
        #     - "#89b4fa" # Blue
        # unstagedChangesColor:
        #     - red # Red
