vim.g.indent_blankline_char = "▎"
vim.g.indent_blankline_char_blankline = "▎"

require("indent_blankline").setup({
    char = "▏",
    show_first_indent_level = true,
    filetype_exclude = {
        "startify",
        "dashboard",
        "dotooagenda",
        "log",
        "fugitive",
        "gitcommit",
        "packer",
        "vimwiki",
        "markdown",
        "json",
        "txt",
        "vista",
        "help",
        "todoist",
        "NvimTree",
        "peekaboo",
        "git",
        "TelescopePrompt",
        "undotree",
        "flutterToolsOutline",
        "", -- for all buffers without a file type
    },
    space_char_blankline = " ",
    show_foldtext = false,
    strict_tabs = true,
    max_indent_increase = 1,
    -- show_current_context = false,
    show_current_context_start = false,
    context_highlight_list = { "IndentBlanklineContext" },
    viewport_buffer = 100,
    buftype_exclude = { "terminal", "nofile" },
    show_trailing_blankline_indent = false,
    use_treesitter_scope = true,
    show_current_context = true,
    context_patterns = {
        "class",
        "function",

        "method",
        "block",
        "list_literal",
        "selector",
        "^if",
        "^table",
        "if_statement",
        "while",
        "for",
        "type",
        "var",

        "import",
    },
})
