local global_local = {
    backup = false,
    cmdheight = 0,
    clipboard = "unnamedplus",
    hidden = true,
    hlsearch = true,
    ignorecase = true,
    mouse = "a",
    pumheight = 10,
    showmode = false,
    showtabline = 2,
    smartcase = true,
    splitbelow = true,
    splitright = true,
    swapfile = false,
    termguicolors = true,
    timeoutlen = 400,
    foldmethod = "indent",
    foldenable = true,
    foldlevel = 99, -- was 1
    foldtext = "v:lua.get_fold_text()",
    foldnestmax = 10,
    undofile = true,
    updatetime = 100,
    writebackup = false,
    expandtab = true,
    shiftwidth = 4,
    tabstop = 4,
    cursorline = true,
    number = true,
    numberwidth = 4,
    signcolumn = "yes",
    wrap = false,
    scrolloff = 8,
    sidescrolloff = 8,
    showcmd = false,
    ruler = false,
    laststatus = 3,
    relativenumber = true,
    linebreak = true,
}

for name, value in pairs(global_local) do
    vim.o[name] = value
end
