add_newline = false

[line_break]
disabled = true

 [character]                         # The name of the module we are configuring is "character"
 success_symbol = "[->](bold green)"  # The "success_symbol" is set to "➜" with color "bold green"
 error_symbol = "[X](bold red)"

[package]
disabled = true

[directory]
style = "bold yellow"

[cmd_duration]
style = "bold purple"

[nodejs]
symbol = "🦕 "
