
# WINDOWRULE v2
# windowrule v2 - position
windowrule = center 1, match:class ([Tt]hunar), match:title (File Operation Progress)
windowrule = center 1, match:class ([Tt]hunar), match:title (Confirm to replace files)
windowrule = center 1, match:title ^(ROG Control)$
windowrule = center 1, match:title ^(Keybindings)$  
windowrule = move 72% 7%,match:title ^(Picture-in-Picture)$ 
windowrule = move 72% 7%,match:title is sharing your screen\.$

# windowrule v2 to avoid idle for fullscreen apps

windowrule = float 1, match:class (xdg-desktop-portal-gtk)
windowrule = float 1, match:class ([Tt]hunar), match:title (File Operation Progress)
windowrule = float 1, match:class ([Tt]hunar), match:title (Confirm to replace files)
windowrule = float 1, match:class ^(file-roller|org.gnome.FileRoller)$
windowrule = float 1, match:class ^(nwg-look|qt6ct)$
windowrule = float 1, match:title (Kvantum Manager)
windowrule = float 1, match:class ^([Qq]alculate-gtk)$

# windowrule v2 - size
windowrule = size 70% 70%, match:class ^(xdg-desktop-portal-gtk)$
